"""
S&P500 銘柄リスト
521銘柄 (stock-heatmap.html から抽出)
形式: (ticker, 企業名)
"""

SP500_TICKERS = [
    ('MSFT', 'Microsoft'),
    ('ORCL', 'Oracle'),
    ('CRM', 'Salesforce'),
    ('ADBE', 'Adobe'),
    ('ACN', 'Accenture'),
    ('IBM', 'IBM'),
    ('INTU', 'Intuit'),
    ('NOW', 'ServiceNow'),
    ('PANW', 'Palo Alto Networks'),
    ('UBER', 'Uber Technologies'),
    ('FTNT', 'Fortinet'),
    ('WDAY', 'Workday'),
    ('SNPS', 'Synopsys'),
    ('CDNS', 'Cadence Design'),
    ('ADSK', 'Autodesk'),
    ('CRWD', 'CrowdStrike'),
    ('ROP', 'Roper Technologies'),
    ('FICO', 'Fair Isaac'),
    ('PAYX', 'Paychex'),
    ('MSI', 'Motorola Solutions'),
    ('DELL', 'Dell Technologies'),
    ('IT', 'Gartner'),
    ('VRSN', 'Verisign'),
    ('GEN', 'Gen Digital'),
    ('ANET', 'Arista Networks'),
    ('MPWR', 'Monolithic Power'),
    ('FFIV', 'F5'),
    ('JKHY', 'Jack Henry'),
    ('PTC', 'PTC'),
    ('CDW', 'CDW'),
    ('AKAM', 'Akamai'),
    ('EPAM', 'EPAM Systems'),
    ('ZBRA', 'Zebra Technologies'),
    ('TYL', 'Tyler Technologies'),
    ('NET', 'Cloudflare'),
    ('DDOG', 'Datadog'),
    ('TEAM', 'Atlassian'),
    ('SMCI', 'Super Micro'),
    ('GDDY', 'GoDaddy'),
    ('FIS', 'Fidelity National'),
    ('FI', 'Fiserv'),
    ('GPN', 'Global Payments'),
    ('LDOS', 'Leidos'),
    ('NTAP', 'NetApp'),
    ('ANSS', 'ANSYS'),
    ('NVDA', 'NVIDIA'),
    ('AVGO', 'Broadcom'),
    ('AMD', 'AMD'),
    ('QCOM', 'Qualcomm'),
    ('TXN', 'Texas Instruments'),
    ('INTC', 'Intel'),
    ('AMAT', 'Applied Materials'),
    ('MU', 'Micron Technology'),
    ('LRCX', 'Lam Research'),
    ('KLAC', 'KLA Corporation'),
    ('MCHP', 'Microchip Technology'),
    ('ADI', 'Analog Devices'),
    ('MRVL', 'Marvell Technology'),
    ('NXPI', 'NXP Semiconductors'),
    ('ON', 'ON Semiconductor'),
    ('FSLR', 'First Solar'),
    ('ENPH', 'Enphase Energy'),
    ('TER', 'Teradyne'),
    ('SWKS', 'Skyworks Solutions'),
    ('QRVO', 'Qorvo'),
    ('AAPL', 'Apple'),
    ('CSCO', 'Cisco Systems'),
    ('HPQ', 'HP'),
    ('HPE', 'Hewlett Packard Ent.'),
    ('JBL', 'Jabil'),
    ('GLW', 'Corning'),
    ('WDC', 'Western Digital'),
    ('STX', 'Seagate Technology'),
    ('TRMB', 'Trimble'),
    ('HUBB', 'Hubbell'),
    ('GOOGL', 'Alphabet Class A'),
    ('META', 'Meta Platforms'),
    ('NFLX', 'Netflix'),
    ('DIS', 'Walt Disney'),
    ('CMCSA', 'Comcast'),
    ('WBD', 'Warner Bros Discovery'),
    ('PARA', 'Paramount Global'),
    ('EA', 'Electronic Arts'),
    ('TTWO', 'Take-Two Interactive'),
    ('LYV', 'Live Nation'),
    ('FOX', 'Fox Corporation Class B'),
    ('FOXA', 'Fox Corporation Class A'),
    ('NWSA', 'News Corp Class A'),
    ('NWS', 'News Corp Class B'),
    ('OMC', 'Omnicom'),
    ('IPG', 'Interpublic Group'),
    ('CHTR', 'Charter Communications'),
    ('DASH', 'DoorDash'),
    ('PINS', 'Pinterest'),
    ('MTCH', 'Match Group'),
    ('LLY', 'Eli Lilly'),
    ('JNJ', 'Johnson & Johnson'),
    ('ABBV', 'AbbVie'),
    ('MRK', 'Merck'),
    ('TMO', 'Thermo Fisher'),
    ('PFE', 'Pfizer'),
    ('AMGN', 'Amgen'),
    ('DHR', 'Danaher'),
    ('BMY', 'Bristol-Myers Squibb'),
    ('GILD', 'Gilead Sciences'),
    ('VRTX', 'Vertex Pharma'),
    ('REGN', 'Regeneron Pharma'),
    ('MRNA', 'Moderna'),
    ('BIIB', 'Biogen'),
    ('IQV', 'IQVIA'),
    ('A', 'Agilent Technologies'),
    ('MTD', 'Mettler-Toledo'),
    ('WAT', 'Waters'),
    ('LH', 'Labcorp'),
    ('DGX', 'Quest Diagnostics'),
    ('WST', 'West Pharmaceutical'),
    ('ZTS', 'Zoetis'),
    ('BIO', 'Bio-Rad Laboratories'),
    ('BAX', 'Baxter'),
    ('VTRS', 'Viatris'),
    ('ILMN', 'Illumina'),
    ('CRL', 'Charles River Labs'),
    ('INCY', 'Incyte'),
    ('TECH', 'Bio-Techne'),
    ('JPM', 'JPMorgan Chase'),
    ('BAC', 'Bank of America'),
    ('WFC', 'Wells Fargo'),
    ('C', 'Citigroup'),
    ('USB', 'U.S. Bancorp'),
    ('PNC', 'PNC Financial'),
    ('TFC', 'Truist Financial'),
    ('MTB', 'M&T Bank'),
    ('FITB', 'Fifth Third Bancorp'),
    ('HBAN', 'Huntington Bancshares'),
    ('RF', 'Regions Financial'),
    ('CFG', 'Citizens Financial'),
    ('KEY', 'KeyCorp'),
    ('FCNCA', 'First Citizens Banc.'),
    ('ZION', 'Zions Bancorporation'),
    ('CMA', 'Comerica'),
    ('V', 'Visa'),
    ('MA', 'Mastercard'),
    ('GS', 'Goldman Sachs'),
    ('MS', 'Morgan Stanley'),
    ('SCHW', 'Charles Schwab'),
    ('BLK', 'BlackRock'),
    ('AXP', 'American Express'),
    ('SPGI', 'S&P Global'),
    ('MCO', "Moody's"),
    ('ICE', 'Intercontinental Exch.'),
    ('CME', 'CME Group'),
    ('COF', 'Capital One Financial'),
    ('AON', 'Aon'),
    ('MMC', 'Marsh & McLennan'),
    ('AJG', 'Arthur J. Gallagher'),
    ('BX', 'Blackstone'),
    ('KKR', 'KKR'),
    ('BRO', 'Brown & Brown'),
    ('MSCI', 'MSCI'),
    ('AMP', 'Ameriprise Financial'),
    ('TROW', 'T. Rowe Price'),
    ('IVZ', 'Invesco'),
    ('NTRS', 'Northern Trust'),
    ('STT', 'State Street'),
    ('BK', 'Bank of New York Mellon'),
    ('DFS', 'Discover Financial'),
    ('SYF', 'Synchrony Financial'),
    ('RJF', 'Raymond James'),
    ('CBOE', 'Cboe Global Markets'),
    ('NDAQ', 'Nasdaq'),
    ('WTW', 'Willis Towers Watson'),
    ('WRB', 'W. R. Berkley'),
    ('EG', 'Everest Group'),
    ('LPLA', 'LPL Financial'),
    ('FDS', 'FactSet Research'),
    ('NLY', 'Annaly Capital'),
    ('AFL', 'Aflac'),
    ('BRK.B', 'Berkshire Hathaway B'),
    ('PGR', 'Progressive'),
    ('CB', 'Chubb'),
    ('MET', 'MetLife'),
    ('TRV', 'Travelers Companies'),
    ('AIG', 'American International'),
    ('ALL', 'Allstate'),
    ('PRU', 'Prudential Financial'),
    ('HIG', 'Hartford Financial'),
    ('L', 'Loews'),
    ('GL', 'Globe Life'),
    ('LNC', 'Lincoln National'),
    ('UNM', 'Unum Group'),
    ('AIZ', 'Assurant'),
    ('CINF', 'Cincinnati Financial'),
    ('MKL', 'Markel'),
    ('RGA', 'Reinsurance Group'),
    ('PFG', 'Principal Financial'),
    ('ERIE', 'Erie Indemnity'),
    ('UNH', 'UnitedHealth'),
    ('ABT', 'Abbott Laboratories'),
    ('ELV', 'Elevance Health'),
    ('CI', 'Cigna'),
    ('HUM', 'Humana'),
    ('CNC', 'Centene'),
    ('MOH', 'Molina Healthcare'),
    ('MDT', 'Medtronic'),
    ('SYK', 'Stryker'),
    ('BSX', 'Boston Scientific'),
    ('ISRG', 'Intuitive Surgical'),
    ('EW', 'Edwards Lifesciences'),
    ('IDXX', 'IDEXX Laboratories'),
    ('MCK', 'McKesson'),
    ('COR', 'Cencora'),
    ('CAH', 'Cardinal Health'),
    ('CVS', 'CVS Health'),
    ('HCA', 'HCA Healthcare'),
    ('UHS', 'Universal Health'),
    ('DVA', 'DaVita'),
    ('DXCM', 'DexCom'),
    ('RMD', 'ResMed'),
    ('ALGN', 'Align Technology'),
    ('VEEV', 'Veeva Systems'),
    ('PODD', 'Insulet'),
    ('STE', 'STERIS'),
    ('HOLX', 'Hologic'),
    ('TFX', 'Teleflex'),
    ('COO', 'Cooper Companies'),
    ('ZBH', 'Zimmer Biomet'),
    ('GEHC', 'GE HealthCare'),
    ('SOLV', 'Solventum'),
    ('GE', 'GE Aerospace'),
    ('RTX', 'RTX'),
    ('HON', 'Honeywell'),
    ('CAT', 'Caterpillar'),
    ('DE', 'Deere'),
    ('BA', 'Boeing'),
    ('LMT', 'Lockheed Martin'),
    ('GD', 'General Dynamics'),
    ('NOC', 'Northrop Grumman'),
    ('LHX', 'L3Harris Technologies'),
    ('ETN', 'Eaton'),
    ('EMR', 'Emerson Electric'),
    ('ITW', 'Illinois Tool Works'),
    ('PH', 'Parker-Hannifin'),
    ('PCAR', 'PACCAR'),
    ('CMI', 'Cummins'),
    ('JCI', 'Johnson Controls'),
    ('TT', 'Trane Technologies'),
    ('IR', 'Ingersoll Rand'),
    ('AME', 'AMETEK'),
    ('DOV', 'Dover'),
    ('XYL', 'Xylem'),
    ('ROK', 'Rockwell Automation'),
    ('FAST', 'Fastenal'),
    ('GWW', 'W.W. Grainger'),
    ('URI', 'United Rentals'),
    ('VLTO', 'Veralto'),
    ('AXON', 'Axon Enterprise'),
    ('CSL', 'Carlisle Companies'),
    ('HWM', 'Howmet Aerospace'),
    ('TDG', 'TransDigm Group'),
    ('WAB', 'Wabtec'),
    ('TXT', 'Textron'),
    ('MAS', 'Masco'),
    ('BLDR', 'Builders FirstSource'),
    ('AOS', 'A.O. Smith'),
    ('ALLE', 'Allegion'),
    ('NDSN', 'Nordson'),
    ('SNA', 'Snap-on'),
    ('IEX', 'IDEX'),
    ('PNR', 'Pentair'),
    ('FTV', 'Fortive'),
    ('GNRC', 'Generac Holdings'),
    ('PWR', 'Quanta Services'),
    ('EMN', 'Eastman Chemical'),
    ('RSG', 'Republic Services'),
    ('VRSK', 'Verisk Analytics'),
    ('BR', 'Broadridge Financial'),
    ('EFX', 'Equifax'),
    ('RKT', 'Rocket Companies'),
    ('AMZN', 'Amazon.com'),
    ('HD', 'Home Depot'),
    ('LOW', "Lowe's"),
    ('TJX', 'TJX Companies'),
    ('ROST', 'Ross Stores'),
    ('BBY', 'Best Buy'),
    ('ULTA', 'Ulta Beauty'),
    ('ORLY', "O'Reilly Automotive"),
    ('AZO', 'AutoZone'),
    ('EBAY', 'eBay'),
    ('CHWY', 'Chewy'),
    ('W', 'Wayfair'),
    ('DLTR', 'Dollar Tree'),
    ('DG', 'Dollar General'),
    ('TPR', 'Tapestry'),
    ('RL', 'Ralph Lauren'),
    ('KMX', 'CarMax'),
    ('LKQ', 'LKQ'),
    ('TSCO', 'Tractor Supply'),
    ('DPZ', "Domino's Pizza"),
    ('GPC', 'Genuine Parts'),
    ('ETSY', 'Etsy'),
    ('WMT', 'Walmart'),
    ('COST', 'Costco Wholesale'),
    ('TGT', 'Target'),
    ('KR', 'Kroger'),
    ('SYY', 'Sysco'),
    ('ACI', 'Albertsons Companies'),
    ('BJ', "BJ's Wholesale"),
    ('KO', 'Coca-Cola'),
    ('PEP', 'PepsiCo'),
    ('PM', 'Philip Morris Intl.'),
    ('MO', 'Altria Group'),
    ('MDLZ', 'Mondelez International'),
    ('KHC', 'Kraft Heinz'),
    ('GIS', 'General Mills'),
    ('MNST', 'Monster Beverage'),
    ('KDP', 'Keurig Dr Pepper'),
    ('STZ', 'Constellation Brands'),
    ('TSN', 'Tyson Foods'),
    ('CAG', 'Conagra Brands'),
    ('K', 'Kellanova'),
    ('MKC', 'McCormick'),
    ('HSY', 'Hershey'),
    ('SJM', 'J. M. Smucker'),
    ('CPB', 'Campbell Soup'),
    ('HRL', 'Hormel Foods'),
    ('ADM', 'Archer-Daniels-Midland'),
    ('BG', 'Bunge'),
    ('LW', 'Lamb Weston'),
    ('BF.B', 'Brown-Forman Class B'),
    ('PG', 'Procter & Gamble'),
    ('CL', 'Colgate-Palmolive'),
    ('KMB', 'Kimberly-Clark'),
    ('EL', 'Estée Lauder'),
    ('CHD', 'Church & Dwight'),
    ('CLX', 'Clorox'),
    ('TSLA', 'Tesla'),
    ('F', 'Ford Motor'),
    ('GM', 'General Motors'),
    ('RIVN', 'Rivian'),
    ('LCID', 'Lucid Group'),
    ('APTV', 'Aptiv'),
    ('BWA', 'BorgWarner'),
    ('NKE', 'Nike'),
    ('LULU', 'Lululemon Athletica'),
    ('DECK', 'Deckers Outdoor'),
    ('DHI', 'D.R. Horton'),
    ('LEN', 'Lennar'),
    ('NVR', 'NVR'),
    ('PHM', 'PulteGroup'),
    ('TOL', 'Toll Brothers'),
    ('WHR', 'Whirlpool'),
    ('MHK', 'Mohawk Industries'),
    ('LEG', 'Leggett & Platt'),
    ('HAS', 'Hasbro'),
    ('MAT', 'Mattel'),
    ('GRMN', 'Garmin'),
    ('PVH', 'PVH'),
    ('TPX', 'Tempur Sealy'),
    ('RVTY', 'Revvity'),
    ('MCD', "McDonald's"),
    ('SBUX', 'Starbucks'),
    ('BKNG', 'Booking Holdings'),
    ('CMG', 'Chipotle Mexican Grill'),
    ('MAR', 'Marriott International'),
    ('HLT', 'Hilton Worldwide'),
    ('YUM', 'Yum! Brands'),
    ('LVS', 'Las Vegas Sands'),
    ('MGM', 'MGM Resorts'),
    ('WYNN', 'Wynn Resorts'),
    ('CZR', 'Caesars Entertainment'),
    ('DRI', 'Darden Restaurants'),
    ('YUMC', 'Yum China'),
    ('EXPE', 'Expedia'),
    ('RCL', 'Royal Caribbean'),
    ('CCL', 'Carnival'),
    ('NCLH', 'Norwegian Cruise Line'),
    ('ABNB', 'Airbnb'),
    ('H', 'Hyatt Hotels'),
    ('POOL', 'Pool Corporation'),
    ('XOM', 'Exxon Mobil'),
    ('CVX', 'Chevron'),
    ('COP', 'ConocoPhillips'),
    ('EOG', 'EOG Resources'),
    ('SLB', 'Schlumberger'),
    ('MPC', 'Marathon Petroleum'),
    ('PSX', 'Phillips 66'),
    ('VLO', 'Valero Energy'),
    ('OXY', 'Occidental Petroleum'),
    ('PXD', 'Pioneer Natural Res.'),
    ('WMB', 'Williams Companies'),
    ('KMI', 'Kinder Morgan'),
    ('OKE', 'ONEOK'),
    ('HES', 'Hess'),
    ('DVN', 'Devon Energy'),
    ('FANG', 'Diamondback Energy'),
    ('HAL', 'Halliburton'),
    ('BKR', 'Baker Hughes'),
    ('TRGP', 'Targa Resources'),
    ('LNG', 'Cheniere Energy'),
    ('EQT', 'EQT'),
    ('MRO', 'Marathon Oil'),
    ('APA', 'APA'),
    ('CTRA', 'Coterra Energy'),
    ('LIN', 'Linde'),
    ('APD', 'Air Products'),
    ('SHW', 'Sherwin-Williams'),
    ('ECL', 'Ecolab'),
    ('FCX', 'Freeport-McMoRan'),
    ('NEM', 'Newmont'),
    ('DOW', 'Dow'),
    ('DD', 'DuPont de Nemours'),
    ('PPG', 'PPG Industries'),
    ('NUE', 'Nucor'),
    ('STLD', 'Steel Dynamics'),
    ('CTVA', 'Corteva'),
    ('IFF', 'Intl Flavors & Frag.'),
    ('CF', 'CF Industries'),
    ('MOS', 'Mosaic'),
    ('VMC', 'Vulcan Materials'),
    ('MLM', 'Martin Marietta'),
    ('PKG', 'Packaging Corp of Am.'),
    ('IP', 'International Paper'),
    ('WRK', 'WestRock'),
    ('AVY', 'Avery Dennison'),
    ('BALL', 'Ball'),
    ('AMCR', 'Amcor'),
    ('CE', 'Celanese'),
    ('LYB', 'LyondellBasell'),
    ('ALB', 'Albemarle'),
    ('FMC', 'FMC'),
    ('NEE', 'NextEra Energy'),
    ('SO', 'Southern Company'),
    ('DUK', 'Duke Energy'),
    ('AEP', 'American Electric Pwr'),
    ('SRE', 'Sempra'),
    ('D', 'Dominion Energy'),
    ('EXC', 'Exelon'),
    ('XEL', 'Xcel Energy'),
    ('ED', 'Consolidated Edison'),
    ('PEG', 'Public Service Ent.'),
    ('PCG', 'PG&E'),
    ('WEC', 'WEC Energy'),
    ('EIX', 'Edison International'),
    ('AWK', 'American Water Works'),
    ('DTE', 'DTE Energy'),
    ('PPL', 'PPL'),
    ('FE', 'FirstEnergy'),
    ('AEE', 'Ameren'),
    ('ETR', 'Entergy'),
    ('ES', 'Eversource Energy'),
    ('CMS', 'CMS Energy'),
    ('CNP', 'CenterPoint Energy'),
    ('ATO', 'Atmos Energy'),
    ('EVRG', 'Evergy'),
    ('LNT', 'Alliant Energy'),
    ('NI', 'NiSource'),
    ('AES', 'AES'),
    ('NRG', 'NRG Energy'),
    ('VST', 'Vistra'),
    ('CEG', 'Constellation Energy'),
    ('PNW', 'Pinnacle West'),
    ('VZ', 'Verizon'),
    ('T', 'AT&T'),
    ('TMUS', 'T-Mobile US'),
    ('UPS', 'United Parcel Service'),
    ('UNP', 'Union Pacific'),
    ('CSX', 'CSX'),
    ('NSC', 'Norfolk Southern'),
    ('FDX', 'FedEx'),
    ('LUV', 'Southwest Airlines'),
    ('DAL', 'Delta Air Lines'),
    ('UAL', 'United Airlines'),
    ('AAL', 'American Airlines'),
    ('ALK', 'Alaska Air Group'),
    ('EXPD', 'Expeditors Intl'),
    ('JBHT', 'J.B. Hunt'),
    ('ODFL', 'Old Dominion Freight'),
    ('CHRW', 'C.H. Robinson'),
    ('WM', 'Waste Management'),
    ('ADP', 'Automatic Data Proc.'),
    ('CTAS', 'Cintas'),
    ('ROL', 'Rollins'),
    ('RHI', 'Robert Half'),
    ('UNF', 'UniFirst'),
    ('WCN', 'Waste Connections'),
    ('FLR', 'Fluor'),
    ('HSIC', 'Henry Schein'),
    ('AMT', 'American Tower'),
    ('PLD', 'Prologis'),
    ('EQIX', 'Equinix'),
    ('WELL', 'Welltower'),
    ('DLR', 'Digital Realty Trust'),
    ('O', 'Realty Income'),
    ('SPG', 'Simon Property Group'),
    ('PSA', 'Public Storage'),
    ('EXR', 'Extra Space Storage'),
    ('CSGP', 'CoStar Group'),
    ('AVB', 'AvalonBay Communities'),
    ('EQR', 'Equity Residential'),
    ('INVH', 'Invitation Homes'),
    ('VICI', 'VICI Properties'),
    ('WPC', 'W. P. Carey'),
    ('IRM', 'Iron Mountain'),
    ('MAA', 'Mid-America Apartment'),
    ('UDR', 'UDR'),
    ('ESS', 'Essex Property Trust'),
    ('ARE', 'Alexandria Real Estate'),
    ('BXP', 'BXP'),
    ('KIM', 'Kimco Realty'),
    ('REG', 'Regency Centers'),
    ('FRT', 'Federal Realty'),
    ('VTR', 'Ventas'),
    ('DOC', 'Healthpeak Properties'),
    ('HST', 'Host Hotels & Resorts'),
    ('SBAC', 'SBA Communications'),
    ('WY', 'Weyerhaeuser'),
    ('AMH', 'American Homes 4 Rent'),
    ('CPT', 'Camden Property Trust'),
    ('GLPI', 'Gaming and Leisure'),
    ('CBRE', 'CBRE Group'),
    ('JLL', 'Jones Lang LaSalle'),
]
